
STRIPE_PUBLISHABLE_KEY: pk_test_ZabszM6zIfmMgpGuAnizTaZ0
STRIPE_SECRET_KEY: sk_test_d0XuOs2BdXMZFQo3yF6GyO6u

# ADD LIVE KEYS BELOW
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
